[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = { 
    "Access-Control-Allow-Origin" = "https://your-frontend-url.netlify.app", 
    "Access-Control-Allow-Credentials" = "true" 
  }
